### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by LeMeteore** [Psycojoker/cubetoolkit#1]
Hey o/ really hope you're doing fine. 
The last time we had a discussion, we talked about automating the cube migration process. The [following](https://gist.github.com/LeMeteore/cac019562822388a5d11c0ead629848c) is attempt to do that. The last bunch of cubes was migrated using this (not complete) script.

I think this script will never be used again, unless there is still some last forgotten cube, waiting somewhere in the dark :\  I've asked to Philippe, who told me to see with you if this script can be merged here.

Let me know o/

**Comment by Psycojoker** [comment]
Hey Patrick :)

It's great to see that you've automated this process! I've integrated it into cubetoolkit and made a new release :) (and fix a bit of things with path to make `cubetoolkit to-newstyle-cube .` works) I've also made you somehow the author of the commit in git.

I'm not sure about this "will never be used again", like I'm working on migrations and we've had to migrate 2 cubes for that and another one is still pending and I'm expecting quite some old private cube to still needed to be migrated.

Thx for your work <3
